DROP TABLE IF EXISTS txm_bitx_staging.align_invoice_header;

CREATE TABLE txm_bitx_staging.align_invoice_header(
invoice_header_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
file_header_id INT NOT NULL,
record_type_code VARCHAR(1),
invoice_number VARCHAR(10),
invoice_id VARCHAR(10),
referral_id VARCHAR(10),
invoice_date DATE,
claim_number VARCHAR(30),
customer_id VARCHAR(10),
authorization_code VARCHAR(30),
client_claim_id VARCHAR(20),
patient_name VARCHAR(50),
ssn VARCHAR(9),
patient_address1 VARCHAR(50),
patient_city VARCHAR(40),
patient_state VARCHAR(2),
patient_zip VARCHAR(5),
patient_phone VARCHAR(10),
patient_date_of_birth DATE,
patient_gender VARCHAR(1),
jurisdiction VARCHAR(2),
date_of_injury DATE,
diagnosis1 VARCHAR(10),
diagnosis_description1 VARCHAR(50),
diagnosis2 VARCHAR(10),
diagnosis_description2 VARCHAR(50),
diagnosis3 VARCHAR(10),
diagnosis_description3 VARCHAR(50),
diagnosis4 VARCHAR(10),
diagnosis_description4 VARCHAR(50),
pay_to_name VARCHAR(20),
pay_to_address1 VARCHAR(50),
pay_to_address2 VARCHAR(50),
pay_to_city VARCHAR(40),
pay_to_state VARCHAR(2),
pay_to_zip VARCHAR(5),
pay_to_fein VARCHAR(9),
pay_to_state_license VARCHAR(20),
pay_to_npi VARCHAR(10),
facility_name VARCHAR(40),
facility_address1 VARCHAR(50),
facility_city VARCHAR(50),
facility_state VARCHAR(2),
facility_zip_code VARCHAR(9),
facility_state_license VARCHAR(20),
facility_npi VARCHAR(10),
referring_provider_name VARCHAR(30),
referring_provider_state_license VARCHAR(20),
referring_provider_npi VARCHAR(10),
provider_fein VARCHAR(20),
provider_state VARCHAR(2),
provider_unique_id VARCHAR(20),
employer_name VARCHAR(40),
service_description VARCHAR(20),
adjuster_name VARCHAR(50),
invoice_total DECIMAL(10,2),
client_total VARCHAR(10),
diagnosis5 VARCHAR(10),
diagnosis_description5 VARCHAR(50),
diagnosis6 VARCHAR(10),
diagnosis_description6 VARCHAR(50),
diagnosis7 VARCHAR(10),
diagnosis_description7 VARCHAR(50),
diagnosis8 VARCHAR(10),
diagnosis_description8 VARCHAR(50),
diagnosis9 VARCHAR(10),
diagnosis_description9 VARCHAR(50),
diagnosis10 VARCHAR(10),
diagnosis_description10 VARCHAR(50),
diagnosis11 VARCHAR(10),
diagnosis_description11 VARCHAR(50),
diagnosis12 VARCHAR(10),
diagnosis_description12 VARCHAR(50),
pre_authorization_number VARCHAR(50),
date_of_service DATE,
create_user VARCHAR(50),
update_user VARCHAR(50),
create_timestamp DATETIME(6),
update_timestamp DATETIME(6),
FOREIGN KEY (file_header_id) REFERENCES align_file_header(file_header_id),
INDEX idx_file_header_id (file_header_id)
);