DROP TABLE IF EXISTS txm_bitx_staging.align_invoice_detail;

CREATE TABLE txm_bitx_staging.align_invoice_detail (
invoice_detail_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
invoice_header_id INT NOT NULL,
record_type_code VARCHAR(1),
line_number VARCHAR(10),
tp_invoice_detail_id VARCHAR(10),
referral_detail_id VARCHAR(10),
skuid VARCHAR(10),
parent_referral_detail_id VARCHAR(10),
start_date DATE,
end_date DATE,
quantity VARCHAR(10),
extended_quantity INT,
hcpcs VARCHAR(10),
modifier VARCHAR(10),
line_item_place_of_service VARCHAR(2),
line_item_emg VARCHAR(1),
line_item_diagnosis_pointer VARCHAR(4),
item_description VARCHAR(100),
line_item_charge_amount DECIMAL(10,2),
line_item_fee_amount DECIMAL(10,2),
line_item_payment_amount DECIMAL(10,2),
line_item_fee_schedule DECIMAL(10,2),
line_item_ucr_amount DECIMAL(10,2),
client_amount VARCHAR(10),
rendering_physician_name VARCHAR(50),
rendering_physician_license_number VARCHAR(20),
rendering_physician_npi VARCHAR(10),
create_user VARCHAR(50),
update_user VARCHAR(50),
create_timestamp DATETIME(6),
update_timestamp DATETIME(6),
FOREIGN KEY (invoice_header_id) REFERENCES align_invoice_header (invoice_header_id),
INDEX idx_invoice_header_id (invoice_header_id)
);
