CREATE TABLE txm_bitx_staging.claim_data(
	claim_data_id INT PRIMARY KEY AUTO_INCREMENT,
	trading_partner VARCHAR(50),
	file_header_id INT ,
	bill_header_id INT ,
	txm_claim_number VARCHAR(15),
	txm_claim_secure BOOLEAN,
	txm_jurisdiction_code VARCHAR(2),
	txm_jurisdiction_description VARCHAR(60),
	patient_first_name VARCHAR(80),
	patient_last_name VARCHAR(80),
	patient_gender VARCHAR(1),
	patient_gender_description VARCHAR(10),
	date_of_birth DATE,
	date_of_injury DATE,
	patient_address_line_1 VARCHAR(80),
	patient_address_line_2 VARCHAR(80),
	patient_city VARCHAR(60),
	patient_state_code VARCHAR(2),
	patient_zip_code VARCHAR(10),
	patient_phone_number int,
	subscriber_name VARCHAR(80),
	subscriber_tax_id VARCHAR(9),
	insured_policy_number VARCHAR(20),
	subscriber_address_line_1 VARCHAR(80),
	subscriber_address_line_2 VARCHAR(80),
	subscriber_city VARCHAR(60),
	subscriber_state VARCHAR(2),
    subscriber_zip_code VARCHAR(10),
	subscriber_telephone_number int,
    social_security_number int,
	create_user VARCHAR(50),
	create_timestamp DATETIME(6),
	update_user VARCHAR(50),
	update_timestamp DATETIME(6),
	CONSTRAINT idx_unique_trading_file_bill UNIQUE (trading_partner,file_header_id,bill_header_id),
	INDEX idx_claim (trading_partner,file_header_id,bill_header_id)
);