create table txm_bitx_staging.claim_denial_data (
claim_denial_data_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
claim_data_id INT,
denial_type_code VARCHAR(100),
denial_type_description VARCHAR(60),
denial_category_code VARCHAR(100),
denial_category_description VARCHAR(60),
denial_status_code VARCHAR(100),
denial_status_description VARCHAR(60),
denial_effective_date DATE,
denial_effectivefrom_date DATE,
denial_effectiveto_date DATE,
reverse_date DATE,
reverse_status_code VARCHAR(100),
reverse_status_description VARCHAR(60),
create_user VARCHAR(50),
create_timestamp datetime(6),
update_user VARCHAR(50),
update_timestamp datetime(6),
FOREIGN KEY (claim_data_id) REFERENCES txm_bitx_staging.claim_data(claim_data_id),
INDEX idx_claim_data_id (claim_data_id)
);