DROP TABLE IF EXISTS txm_bitx_staging.jopari_bill_header_record_10;

CREATE TABLE txm_bitx_staging.jopari_bill_header_record_10 (
bill_header_id Int NOT NULL PRIMARY KEY AUTO_INCREMENT,
file_header_id Int NOT NULL,
record_type_code VARCHAR(2),
unique_bill_id VARCHAR(15),
bill_form_type VARCHAR(4),
claim_type VARCHAR(2),
submitter_bill_id_num VARCHAR(32),
ocr_image_id VARCHAR(32),
billing_prov_unique_bill_id VARCHAR(32),
patient_last_name VARCHAR(80),
patient_middle_name VARCHAR(25),
patient_first_name VARCHAR(25),
patient_last_name_suffix VARCHAR(15),
patient_address1 VARCHAR(80),
patient_address2 VARCHAR(80),
patient_city VARCHAR(60),
patient_state_code VARCHAR(2),
patient_postal_code VARCHAR(9),
patient_country_code VARCHAR(2),
patient_phone_num VARCHAR(15),
patient_dob DATE,
patient_gender_code VARCHAR(1),
patient_marital_status_code VARCHAR(1),
patient_employement_status VARCHAR(2),
patient_student_status VARCHAR(1),
patient_SSN VARCHAR(9),
employer_name VARCHAR(80),
indexed_claim_num VARCHAR(32),
reported_claim_num VARCHAR(32),
patient_account_num VARCHAR(32),
patient_medical_record_num VARCHAR(32),
total_charge_per_bill bigint,
outside_lab_charges bigint,
accident_cause1 VARCHAR(2),
accident_cause2 VARCHAR(2),
accident_cause3 VARCHAR(2),
accident_state VARCHAR(2),
facility_code VARCHAR(2),
bill_frequency_type_code VARCHAR(1),
bill_submission_reason_code VARCHAR(2),
original_reference_num VARCHAR(15),
provider_signature_on_file_ind VARCHAR(1),
provider_accepts_assignment VARCHAR(1),
assignment_of_benefits_ind VARCHAR(1),
patient_signature_source_code VARCHAR(1),
contract_type_code VARCHAR(2),
from_service_bill_date DATE,
thru_service_bill_date DATE,
date_of_bill DATE,
date_bill_received_by_payer DATE,
date_of_injury DATE,
date_of_onset_similar_symptoms DATE,
prescription_bill_date DATE,
disability_begin_date DATE,
diability_end_date DATE,
admission_date DATE,
discharge_date DATE,
bill_class_code VARCHAR(4),
payer_assigned_pay_code VARCHAR(16),
create_user VARCHAR(50),
update_user VARCHAR(50),
create_timestamp DATETIME(6),
update_timestamp DATETIME(6),
FOREIGN KEY (file_header_id) REFERENCES jopari_file_header_record_01 (file_header_id),
INDEX idx_file_header_id (file_header_id),
INDEX idx_unique_bill_id (unique_bill_id),
INDEX idx_bill_form_type (bill_form_type)
);