DROP TABLE IF EXISTS txm_bitx_staging.jopari_subscriber_record_13;

CREATE TABLE txm_bitx_staging.jopari_subscriber_record_13 (
subscriber_header_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
bill_header_id INT NOT NULL,
record_type_code VARCHAR(2),
unique_bill_id VARCHAR(15),
priority VARCHAR(1),
patient_relationship_to_subscriber VARCHAR(2),
treatment_authorization_num VARCHAR(30),
total_prior_payment bigint,
total_estimated_amount_due bigint,
subscriber_last_name VARCHAR(80),
subscriber_first_name VARCHAR(25),
subscriber_middle_name VARCHAR(25),
subscriber_address1 VARCHAR(80),
subscriber_address2 VARCHAR(80),
subscriber_city VARCHAR(60),
subscriber_state_code VARCHAR(2),
subscriber_postal_code VARCHAR(9),
subscriber_country_code VARCHAR(2),
subscriber_phone_num VARCHAR(15),
date_of_birth DATE,
gender_code VARCHAR(1),
tin_type VARCHAR(1),
tin VARCHAR(9),
release_of_info_code VARCHAR(1),
release_of_info_date DATE,
member_id VARCHAR(30),
group_num VARCHAR(30),
plan_name VARCHAR(60),
payer_name VARCHAR(120),
payer_address1 VARCHAR(80),
payer_address2 VARCHAR(80),
payer_city VARCHAR(60),
payer_state VARCHAR(2),
payer_zip_code VARCHAR(9),
payer_country_code VARCHAR(2),
payer_phone VARCHAR(15),
sender_payer_id VARCHAR(32),
NAIC_num VARCHAR(10),
create_user VARCHAR(50),
create_timestamp DATETIME(6),
update_user VARCHAR(50),
update_timestamp DATETIME(6),
FOREIGN KEY (bill_header_id) REFERENCES jopari_bill_header_record_10 (bill_header_id),
INDEX idx_bill_header_id (bill_header_id)
);