DROP TABLE IF EXISTS txm_bitx_staging.Jopari_bill_provider_record_12;

CREATE TABLE txm_bitx_staging.jopari_bill_provider_record_12(
bill_provider_header_id Int  NOT NULL PRIMARY KEY AUTO_INCREMENT,
bill_header_id Int NOT NULL,
record_type_code VARCHAR(2),
unique_bill_id VARCHAR(15),
billing_provider_name VARCHAR(120),
billing_provider_address1 VARCHAR(80),
billing_provider_address2 VARCHAR(80),
billing_provider_city VARCHAR(60),
billing_provider_state VARCHAR(2),
billing_zip_code VARCHAR(9),
billing_provider_country_code VARCHAR(2),
billing_provider_tax_id VARCHAR(9),
billing_provider_state_license VARCHAR(30),
billing_provider_NPI VARCHAR(10),
sender_billing_provider_id VARCHAR(32),
pay_to_provider_name VARCHAR(120),
pay_to_provider_address1 VARCHAR(80),
pay_to_provider_address2 VARCHAR(80),
pay_to_provider_city VARCHAR(60),
pay_to_provider_state VARCHAR(2),
pay_to_zip_code VARCHAR(9),
pay_to_provider_country VARCHAR(2),
pay_to_provider_tax_id VARCHAR(9),
pay_to_provider_state_license VARCHAR(30),
Pay_to_provider_NPI VARCHAR(10),
sender_pay_to_provider_id VARCHAR(32),
service_facility_name VARCHAR(120),
service_facility_address1 VARCHAR(80),
service_facility_address2 VARCHAR(80),
service_facility_city VARCHAR(60),
service_facility_state VARCHAR(2),
service_facility_zip_code VARCHAR(9),
service_facility_country VARCHAR(2),
service_facility_provider_state_license VARCHAR(30),
service_facility_provider_NPI VARCHAR(10),
create_user VARCHAR(50),
update_user VARCHAR(50),
create_timestamp DATETIME(6),
update_timestamp DATETIME(6),
FOREIGN KEY (bill_header_id) REFERENCES jopari_bill_header_record_10 (bill_header_id),
INDEX idx_bill_header_id (bill_header_id)
);