DROP TABLE IF EXISTS txm_bitx_staging.jopari_bill_detail_record_50;
CREATE TABLE txm_bitx_staging.jopari_bill_detail_record_50 (
bill_detail_record_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
bill_header_id INT NOT NULL,
record_type_code VARCHAR(2),
unique_bill_id VARCHAR(15),
line_number Int,
service_from_date DATE,
service_thru_date DATE,
procedure_code_qualifier VARCHAR(2),
procedure_code VARCHAR(8),
hcpcs_modifier_code_1 VARCHAR(2),
hcpcs_modifier_code_2 VARCHAR(2),
hcpcs_modifier_code_3 VARCHAR(2),
hcpcs_modifier_code_4 VARCHAR(2),
procedure_description VARCHAR(80),
revenue_code VARCHAR(4),
place_of_service_code VARCHAR(2),
type_of_service_code VARCHAR(2),
diagnosis_pointer_1 Int,
diagnosis_pointer_2 Int,
diagnosis_pointer_3 Int,
diagnosis_pointer_4 Int,
day_unit_code VARCHAR(2),
day_unit_qty Decimal(6,1),
prior_authorization VARCHAR(32),
revenue_unit_rate Decimal(10,2),
total_charge_per_line Decimal(10,2),
sales_tax Decimal(6,2),
create_user VARCHAR(50),
update_user VARCHAR(50),
create_timestamp DATETIME(6),
update_timestamp DATETIME(6),
FOREIGN KEY (bill_header_id) REFERENCES jopari_bill_header_record_10 (bill_header_id),
INDEX idx_bill_header_id (bill_header_id,line_number)
);