DROP TABLE IF EXISTS txm_bitx_staging.techhealth_invoice_header;

CREATE TABLE txm_bitx_staging.techhealth_invoice_header (
invoice_header_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
file_header_id INT NOT NULL,
record_type_code varchar(1),
invoice_number varchar(10),
invoice_id varchar(10),
referral_id varchar(10),
invoice_date date,
claim_number varchar(30),
customer_id varchar(10),
authorization_code varchar(30),
client_claim_id varchar(20),
patient_name varchar(50),
ssn varchar(9),
patient_address1 varchar(50),
patient_city varchar(40),
patient_state varchar(2),
patient_zip varchar(5),
patient_phone varchar(10),
patient_date_of_birth date,
patient_gender varchar(1),
jurisdiction varchar(2),
date_of_injury date,
diagnosis1 varchar(10),
diagnosis_description1 varchar(50),
diagnosis2 varchar(10),
diagnosis_description2 varchar(50),
diagnosis3 varchar(10),
diagnosis_description3 varchar(50),
diagnosis4 varchar(10),
diagnosis_description4 varchar(50),
pay_to_name varchar(20),
pay_to_address1 varchar(50),
pay_to_address2 varchar(50),
pay_to_city varchar(40),
pay_to_state varchar(2),
pay_to_zip varchar(5),
pay_to_fein varchar(9),
pay_to_state_license varchar(20),
pay_to_npi varchar(10),
facility_name varchar(40),
facility_address1 varchar(50),
facility_city varchar(50),
facility_state varchar(2),
facility_zip_code varchar(9),
facility_state_license varchar(20),
facility_npi varchar(10),
referring_provider_name varchar(30),
referring_provider_state_license varchar(20),
referring_provider_npi varchar(10),
provider_fein varchar(20),
provider_state varchar(2),
provider_unique_id varchar(20),
employer_name varchar(40),
service_description varchar(20),
adjuster_name varchar(50),
invoice_total decimal(10,2),
client_total varchar(10),
diagnosis5 varchar(10),
diagnosis_description5 varchar(50),
diagnosis6 varchar(10),
diagnosis_description6 varchar(50),
diagnosis7 varchar(10),
diagnosis_description7 varchar(50),
diagnosis8 varchar(10),
diagnosis_description8 varchar(50),
diagnosis9 varchar(10),
diagnosis_description9 varchar(50),
diagnosis10 varchar(10),
diagnosis_description10 varchar(50),
diagnosis11 varchar(10),
diagnosis_description11 varchar(50),
diagnosis12 varchar(10),
diagnosis_description12 varchar(50),
pre_authorization_number varchar(50),
date_of_service date,
create_user VARCHAR(50),
update_user VARCHAR(50),
create_timestamp DATETIME(6),
update_timestamp DATETIME(6),
FOREIGN KEY (file_header_id) REFERENCES techhealth_file_header(file_header_id),
INDEX idx_file_header_id (file_header_id)
);