DROP TABLE IF EXISTS txm_bitx_staging.techhealth_invoice_detail;

CREATE TABLE txm_bitx_staging.techhealth_invoice_detail (
invoice_detail_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
invoice_header_id INT NOT NULL,
record_type_code varchar(1),
line_number varchar(10),
tp_invoice_detail_id varchar(10),
referral_detail_id varchar(10),
skuid varchar(10),
parent_referral_detail_id varchar(10),
start_date date,
end_date date,
quantity varchar(10),
extended_quantity int,
hcpcs varchar(10),
modifier varchar(10),
line_item_place_of_service varchar(2),
line_item_emg varchar(1),
line_item_diagnosis_pointer varchar(4),
item_description varchar(100),
line_item_charge_amount decimal(10,2),
line_item_fee_amount decimal(10,2),
line_item_payment_amount decimal(10,2),
line_item_fee_schedule decimal(10,2),
line_item_ucr_amount decimal(10,2),
client_amount varchar(10),
rendering_physician_name varchar(50),
rendering_physician_license_number varchar(20),
rendering_physician_npi varchar(10),
create_user VARCHAR(50),
update_user VARCHAR(50),
create_timestamp DATETIME(6),
update_timestamp DATETIME(6),
FOREIGN KEY (invoice_header_id) REFERENCES techhealth_invoice_header(invoice_header_id),
INDEX idx_invoice_header_id (invoice_header_id)
);