CREATE TABLE txm_bitx_logs.batch_step_function_master (
    sf_batch_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Step Function Batch ID',
    source VARCHAR(50) NOT NULL COMMENT 'Source',
    trading_partner VARCHAR(50) COMMENT 'Trading Partner',
    file_header_id INT COMMENT 'File Header ID',
    file_name VARCHAR(100) COMMENT 'File Name',
    attachment_file_name VARCHAR(100) COMMENT 'Attachment File Name',
	invoke_payload VARCHAR(1000) COMMENT 'Input Invoke Payload',
    staging_data_pipeline_id VARCHAR(255) COMMENT 'Staging AWS Step Functions ID',
    staging_payload VARCHAR(1000) COMMENT 'Input Staging Payload',
    enhanced_data_pipeline_id VARCHAR(255) COMMENT 'Enhanced AWS Step Functions ID',
    enhanced_payload VARCHAR(1000) COMMENT 'Input Enhanced Payload',
    enrichment_data_pipeline_id VARCHAR(255) COMMENT 'Enrichment AWS Step Functions ID',
    enrichment_payload VARCHAR(1000) COMMENT 'Input Enrichment Payload',
	status_type VARCHAR(100) COMMENT 'Status Type - STAGING, ENHANCED, ENRICHMENT',
    status VARCHAR(100) COMMENT 'Status',
    reprocess_flag VARCHAR(1) COMMENT 'Reprocess Flag Y/N',
    start_datetime DATETIME(6) NOT NULL,
    end_datetime DATETIME(6),
    update_timestamp DATETIME(6) NOT NULL COMMENT 'Update Timestamp',
    create_user VARCHAR(50) NOT NULL COMMENT 'Create User',
    update_user VARCHAR(50) NOT NULL COMMENT 'Update User',
    INDEX idx_master (source, trading_partner, file_header_id),
    INDEX idx_reprocess_flag (reprocess_flag)
);