DROP TABLE IF EXISTS txm_bitx_provider.provider;

CREATE TABLE txm_bitx_provider.provider (
 provider_number VARCHAR(20) NOT NULL UNIQUE PRIMARY KEY,
 provider_entity_type VARCHAR(1),
 provider_type_code VARCHAR(3),
 bill_item_type VARCHAR(10),
 rendering_provider_name VARCHAR(120),
 rendering_provider_npi VARCHAR(10),
 rendering_provider_license VARCHAR(30),
 rendering_provider_jurisdiction VARCHAR(4),
 vendor_tax_id VARCHAR(9),
 vendor_tax_id_indicator VARCHAR(1),
 vendor_number VARCHAR(60),
 vendor_name VARCHAR(140),
 vendor_license_type VARCHAR(3),
 vendor_address1 VARCHAR(80),
 vendor_address2 VARCHAR(80),
 vendor_city VARCHAR(60),
 vendor_state VARCHAR(2),
 vendor_zip_code VARCHAR(10),
 vendor_phone BIGINT,
 vendor_status VARCHAR(10) DEFAULT 'Active',
 vendor_dba VARCHAR(50),
 facility_name VARCHAR(120),
 facility_npi VARCHAR(10),
 facility_address_1 VARCHAR(80),
 facility_address_2 VARCHAR(80),
 facility_city VARCHAR(60),
 facility_state VARCHAR(2),
 facility_zip_code VARCHAR(10),
 udf_data_value VARCHAR(1),
 delivered_to_sa VARCHAR(10) DEFAULT 'NEW',
 create_user VARCHAR(50),
 update_user VARCHAR(50),
 create_timestamp DATETIME(6),
 update_timestamp DATETIME(6),
 INDEX idx_provider_lookup (vendor_tax_id, (UPPER(rendering_provider_license)), rendering_provider_npi, (UPPER(vendor_number)), (UPPER(facility_address_1)), (UPPER(facility_city)), (UPPER(facility_state)), (UPPER(facility_zip_code)))
);