DROP TABLE IF EXISTS kofax_dwc066;

CREATE TABLE txm_bitx_kofax_staging.kofax_dwc066(
    dwc_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    header_id INT NULL,
    invoice_number VARCHAR(12),
    claim_number VARCHAR(15),
    receive_date DATE,
    special_handling VARCHAR(3),
    provider_id BIGINT,
    vendor_name VARCHAR(35),
    vendor_address_1 VARCHAR(35),
    vendor_address_2 VARCHAR(35),
    vendor_city  VARCHAR(30),
    vendor_state VARCHAR(2),
    vendor_zip_code VARCHAR(11),
    vendor_federal_employer_id_number VARCHAR(9),
    invoice_date DATE,
    facility_name VARCHAR(35),
    facility_address_1 VARCHAR(35),
    facility_address_2 VARCHAR(35),
    facility_city VARCHAR(30),
    facility_state VARCHAR(2),
    facility_zip_code VARCHAR(11),
    facility_npi INT,
    patient_first_name VARCHAR(35),
    patient_middle_name VARCHAR(35),
    patient_last_name VARCHAR(35),
    patient_social_security_number INT,
    patient_dob DATE,
    patient_date_of_injury DATE,
    prescribingdoctor_firstname VARCHAR(35),
    prescribingdoctor_lastname VARCHAR(35),
    prescribingdoctor_nationalproviderid INT,
    create_user VARCHAR(50),
    create_timestamp DATETIME(6),
    update_user VARCHAR(50),
    update_timestamp DATETIME(6),
    FOREIGN KEY (header_id) REFERENCES kofax_header(header_id),
    INDEX idx_header_id (header_id)
);