DROP TABLE IF EXISTS kofax_cms1500;

CREATE TABLE txm_bitx_kofax_staging.kofax_cms1500(
    cms_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    header_id INT NULL,
    invoice_number VARCHAR(12),
    claim_number VARCHAR(15),
    receive_date DATE,
    special_handling VARCHAR(3),
    provider_id BIGINT,
    vendor_name VARCHAR(35),
    vendor_address_1 VARCHAR(35),
    vendor_address_2 VARCHAR(35),
    vendor_city VARCHAR(30),
    vendor_state VARCHAR(2),
    vendor_zip_code VARCHAR(11),
    vendor_federal_employer_id_number VARCHAR(9),
    vendor_npi INT,
    vendor_other_id VARCHAR(20),
    facility_name VARCHAR(35),
    facility_address_1 VARCHAR(35),
    facility_address_2 VARCHAR(35),
    facility_city VARCHAR(30),
    facility_state VARCHAR(2),
    facility_zip_code VARCHAR(11),
    facility_npi INT,
    facility_other_id VARCHAR(20),
    patient_first_name VARCHAR(35),
    patient_middle_name VARCHAR(35),
    patient_last_name VARCHAR(35),
    patient_social_security_number INT,
    patient_dob DATE,
    patient_date_of_injury DATE,
    patient_account_number VARCHAR(30),
    referring_provider_fullname VARCHAR(35),
    referring_provider_other_id VARCHAR(20),
    referrring_provider_npi INT,
    signing_provider_full_name VARCHAR(35),
    signing_provider_date DATE,
    diagnosis_icd_indicator VARCHAR(1),
    diagnosis_code_A VARCHAR(10),
    diagnosis_code_B VARCHAR(10),
    diagnosis_code_C VARCHAR(10),
    diagnosis_code_D VARCHAR(10),
    diagnosis_code_E VARCHAR(10),
    diagnosis_code_F VARCHAR(10),
    diagnosis_code_G VARCHAR(10),
    diagnosis_code_H VARCHAR(10),
    diagnosis_code_I VARCHAR(10),
    diagnosis_code_J VARCHAR(10),
    diagnosis_code_K VARCHAR(10),
    diagnosis_code_L VARCHAR(10),
    total_charge DECIMAL(11,2),
    create_user VARCHAR(50),
    create_timestamp DATETIME(6),
    update_user VARCHAR(50),
    update_timestamp DATETIME(6),
    FOREIGN KEY (header_id) REFERENCES kofax_header(header_id),
    INDEX idx_header_id (header_id)
);