DROP TABLE IF EXISTS txm_bitx.bill_header;

CREATE TABLE txm_bitx.bill_header (
    bill_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    bill_header_id INT,
    file_header_id INT,
    source VARCHAR(25) DEFAULT 'ebill',
    trading_partner VARCHAR(50),
    form_type VARCHAR(50),
    txm_invoice_number BIGINT UNIQUE,
    unique_bill_id VARCHAR(15),
    invoice_id VARCHAR(10),
    invoice_number VARCHAR(10),
    invoice_date DATE,
    customer_id VARCHAR(10),
    reported_claim_number VARCHAR(32),
    txm_claim_number VARCHAR(15),
    client_claim_id VARCHAR(20),
    insurance_carrier_claim_number VARCHAR(15),
    document_control_number VARCHAR(32),
    date_of_bill DATE,
    date_bill_received_by_payer DATE,
    bill_class_code VARCHAR(4),
    bill_frequency_type_code VARCHAR(5),
    facility_code VARCHAR(5),
    contract_type_code VARCHAR(2),
    jurisdiction VARCHAR(2),
    referral_id VARCHAR(10),
    authorization_code VARCHAR(30),
    sequence VARCHAR(5),
    resubmission_code varchar(2),
    original_reference_number varchar(15),
    pre_authorization_number VARCHAR(50),
    txm_claim_secure tinyint(1),
    txm_jurisdiction_code VARCHAR(2),
    txm_jurisdiction_description VARCHAR(60),
    error_code VARCHAR(1),
    bill_type VARCHAR(1),
    network VARCHAR(1),
    special_handling VARCHAR(3),
    sequence_number INT,
    explanation_of_benefits	varchar(50),
    pec	varchar(10),
    total_tax_amount DECIMAL(10,2),
    system_indicator varchar(1),
    provider_signature_indicator VARCHAR(1),
    manual_vendormatch_request_response varchar(400),
    manual_claimmatch_request_response  varchar(400),
    manual_review_flag VARCHAR(10),
    manual_review_reason VARCHAR(100),
    create_user VARCHAR(50),
    create_timestamp DATETIME(6),
    update_user VARCHAR(50),
    update_timestamp DATETIME(6),
    INDEX idx_bill_header_id (bill_header_id),
    INDEX idx_source_file_tp (source,trading_partner,file_header_id),
    INDEX idx_form_type (form_type),
    INDEX idx_txm_invoice_number (txm_invoice_number),
    INDEX idx_unique_bill_id (unique_bill_id)
);