DROP TABLE IF EXISTS txm_bitx.patient;

CREATE TABLE txm_bitx.patient (
    patient_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    bill_id INT,
    social_security_number varchar(11),
    patient_account_number VARCHAR(32),
    patient_control_number VARCHAR(32),
    patient_medical_record_number VARCHAR(32),
    patient_name VARCHAR(145),
    date_of_birth DATE,
    patient_gender VARCHAR(1),
    patient_marital_status_code VARCHAR(1),
    patient_address_line_1 VARCHAR(80),
    patient_address_line_2 VARCHAR(80),
    patient_city VARCHAR(60),
    patient_state_code VARCHAR(2),
    patient_country_code VARCHAR(2),
    zip_code VARCHAR(9),
    patient_phone_number BIGINT,
    patient_relationship_to_insured VARCHAR(2),
    date_of_injury DATE,
    accident_state VARCHAR(2),
    automobile_accident VARCHAR(2),
    other_accident VARCHAR(2),
    accept_assignment_indicator VARCHAR(1),
    patient_gender_description VARCHAR(10),
    create_user VARCHAR(50),
    create_timestamp DATETIME(6),
    update_user VARCHAR(50),
    update_timestamp DATETIME(6),
    FOREIGN KEY (bill_id) REFERENCES bill_header(bill_id),
    INDEX idx_bill_id (bill_id)
);