DROP TABLE IF EXISTS txm_bitx.pharmacy_line;

CREATE TABLE txm_bitx.pharmacy_line(
	pharmacy_line_id int NOT NULL PRIMARY KEY auto_increment, 
	bill_id int,
	line_number INT,
	dispensed varchar(1),
    generic_available varchar(11),
	dispensed_as_written_code varchar(1),
	prescription_date date, 
	ndc_code varchar(11),
	quantity int,
	days_supply int, 
	fill_count int,
	drug_name varchar(80), 
	prescription_number varchar(15),
	total_charge_per_bill decimal(10,2),
	preauthorization_number varchar(30), 
	basis_of_cost_deter_code int,
	usual_customary_charge decimal(10,2), 
	dispensing_fee decimal(10,2), 
	date_received date, 
	bill_calculation_date date,
	service_from_date date,
	service_thru_date date,
	tax_amount decimal(10,2), 
	charged_amount decimal(10,2),
	recom_amount decimal(10,2), 
	fee_schedule decimal(10,2), 
	contract_amount decimal(10,2),
	cost_amount decimal(10,2), 
	total_prior_payments int,
	ppo_reductions decimal(10,2),
	name_brand_ndc VARCHAR(15),
	diagnosis_pointer_1 VARCHAR(2),
	diagnosis_pointer_2 VARCHAR(2),
	diagnosis_pointer_3 VARCHAR(2),
	diagnosis_pointer_4 VARCHAR(2),
	generic_dispensed VARCHAR(1),
	recommended_amount VARCHAR(10),
    create_user VARCHAR(50),
    create_timestamp DATETIME(6),
    update_user VARCHAR(50),
    update_timestamp DATETIME(6),
	foreign key (bill_id) references bill_header (bill_id),
    INDEX idx_bill_id (bill_id)
);
