DROP TABLE IF EXISTS txm_bitx.professional_treatment_line;

CREATE TABLE txm_bitx.professional_treatment_line (
    treatment_line_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    treatment_id INT,
    bill_id INT,
    line_number INT,
    referral_detail_id VARCHAR(10),
    service_date_from DATE,
    service_date_to DATE,
    place_of_service_code VARCHAR(2),
    procedure_code VARCHAR(10),
    procedure_code_modifier_1 VARCHAR(2),
    procedure_code_modifier_2 VARCHAR(2),
    procedure_code_modifier_3 VARCHAR(4),
    procedure_code_modifier_4 VARCHAR(4),
    diagnosis_pointer_1 VARCHAR(2),
    diagnosis_pointer_2 VARCHAR(2),
    diagnosis_pointer_3 VARCHAR(2),
    diagnosis_pointer_4 VARCHAR(2),
    charges_for_services DECIMAL(10,2),
    units DECIMAL(6,1),
    emergency_service_indicator VARCHAR(1),
    parent_referral_detail_id VARCHAR(10),
    line_item_fee_amount DECIMAL(10,2),
    prior_authorization VARCHAR(32),
    sales_tax DECIMAL(6,2),
    ppo_reductions DECIMAL(10,2),
    skuid VARCHAR(10),
    create_user VARCHAR(50),
    create_timestamp DATETIME(6),
    update_user VARCHAR(50),
    update_timestamp DATETIME(6),
    FOREIGN KEY (treatment_id) REFERENCES professional_treatment(treatment_id),
    INDEX idx_treatment_id (treatment_id),
    INDEX idx_bill_id (bill_id)
);
