DROP TABLE IF EXISTS txm_bitx.provider;

CREATE TABLE txm_bitx.provider (
    provider_id  INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    provider_number VARCHAR(20),
    bill_id INT,
    rendering_record_type_physician_code VARCHAR(20),
    rendering_provider_name VARCHAR(120),
    rendering_provider_license VARCHAR(30),
    rendering_provider_npi VARCHAR(10),
    rendering_provider_nabp VARCHAR(10),
    rendering_provider_dea_number VARCHAR(12),
    rendering_provider_taxonomy_code VARCHAR(10),
    rendering_provider_date DATE,
    rendering_provider_other_id VARCHAR(30),
    referring_record_type_physician_code varchar(20),
    rendering_physician_name VARCHAR(50),
    rendering_physician_npi VARCHAR(10), 
    referring_provider_name VARCHAR(130),
    referring_provider_address_1 VARCHAR(80),
    referring_provider_address_2 VARCHAR(80),
    referring_provider_city VARCHAR(60),
    referring_provider_state VARCHAR(2),
    referring_provider_zip_code VARCHAR(9),
    referring_provider_state_license VARCHAR(30),
    referring_provider_npi VARCHAR(30),
    referring_provider_nabp VARCHAR(10),
    referring_provider_dea_number VARCHAR(12),
    referring_provider_taxonomy_code VARCHAR(10),
    referring_provider_other_id VARCHAR(80),
    facility_name VARCHAR(120),
    facility_address_1 VARCHAR(80),
    facility_address_2 VARCHAR(80),
    facility_city VARCHAR(60),
    facility_state VARCHAR(2),
    facility_zip_code VARCHAR(11),
    facility_npi VARCHAR(10),
    facility_other_id VARCHAR(30),
    facility_tax_id VARCHAR(9),
    vendor_record_type_physician_code VARCHAR(20),
    vendor_number VARCHAR(60),
    vendor_name VARCHAR(140),
    vendor_address_1 VARCHAR(80),
    vendor_address_2 VARCHAR(80),
    vendor_city VARCHAR(60),
    vendor_state VARCHAR(2),
    vendor_country VARCHAR(2),
    vendor_zip_code VARCHAR(10),
    vendor_phone_number bigint,
    vendor_npi VARCHAR(10),
    vendor_tax_id VARCHAR(9),
    vendor_other_id VARCHAR(30),
    vendor_dba VARCHAR(50),
    vendor_legalname VARCHAR(500),
    pay_to_provider_state_license VARCHAR(30),
    pay_to_provider_NPI VARCHAR(10),
    additional_name VARCHAR(140),
    operating_provider_first_name VARCHAR(80),
    operating_provider_last_name VARCHAR(80),
    operating_provider_national_provider_id VARCHAR(30),
    operating_provider_other_id VARCHAR(20),
    attending_provider_first_name VARCHAR(35),
    attending_provider_last_name VARCHAR(35),
    attending_provider_national_provider_id VARCHAR(10),
    attending_provider_other_id VARCHAR(20),
    signing_provider_full_name VARCHAR(35),
    signing_provider_date DATE,
    federal_military_treatment_facility VARCHAR(1),
    create_user VARCHAR(50),
    create_timestamp DATETIME(6),
    update_user VARCHAR(50),
    update_timestamp DATETIME(6),
    FOREIGN KEY (bill_id) REFERENCES txm_bitx.bill_header(bill_id),
    INDEX idx_bill_id (bill_id)
);